services:
  - type: web
    name: prometheus-web
    env: node
    plan: free
    buildCommand: |
      apt update &&
      apt install -y luajit git &&
      git clone https://github.com/prometheus-lua/Prometheus.git &&
      npm install
    startCommand: node server.js
